# NextGCore AMF Communication Service OpenAPI Specification
# Based on 3GPP TS 29.518 v18.6.0

openapi: 3.0.3
info:
  title: AMF Communication Service
  version: 1.3.0
  description: AMF Communication Service (namf-comm) per 3GPP TS 29.518

servers:
  - url: "{apiRoot}/namf-comm/v1"
    variables:
      apiRoot:
        default: http://localhost:7777

paths:
  /ue-contexts/{ueContextId}:
    get:
      summary: Get UE context
      operationId: GetUeContext
      parameters:
        - $ref: "#/components/parameters/UeContextId"
      responses:
        "200":
          description: UE context retrieved
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UeContext"
        "404":
          $ref: "#/components/responses/NotFound"

  /ue-contexts/{ueContextId}/assign-ebi:
    post:
      summary: Assign EBI for PDU session
      operationId: AssignEbi
      parameters:
        - $ref: "#/components/parameters/UeContextId"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AssignEbiData"
      responses:
        "200":
          description: EBI assigned
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AssignedEbiData"

  /ue-contexts/{ueContextId}/transfer:
    post:
      summary: Transfer UE context (handover)
      operationId: CreateUeContextTransfer
      parameters:
        - $ref: "#/components/parameters/UeContextId"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UeContextTransferReqData"
      responses:
        "200":
          description: UE context transfer complete
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UeContextTransferRspData"

  /non-ue-n2-messages/transfer:
    post:
      summary: Non-UE N2 message transfer
      operationId: NonUeN2MessageTransfer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/N2InformationTransferReqData"
      responses:
        "200":
          description: Transfer successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/N2InformationTransferRspData"

  /subscriptions:
    post:
      summary: Subscribe to AMF status changes
      operationId: AMFStatusChangeSubscribe
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SubscriptionData"
      responses:
        "201":
          description: Subscription created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SubscriptionData"

components:
  parameters:
    UeContextId:
      name: ueContextId
      in: path
      required: true
      schema:
        type: string

  schemas:
    UeContext:
      type: object
      properties:
        supi:
          type: string
        pei:
          type: string
        gpsi:
          type: string
        amfUeNgapId:
          type: integer
          format: int64
        ranUeNgapId:
          type: integer
        registrationState:
          type: string
          enum: [REGISTERED, DEREGISTERED]
        accessType:
          type: string
          enum: [3GPP_ACCESS, NON_3GPP_ACCESS]
        guami:
          $ref: "#/components/schemas/Guami"
        servingNetworkName:
          type: string

    Guami:
      type: object
      required: [plmnId, amfId]
      properties:
        plmnId:
          $ref: "#/components/schemas/PlmnId"
        amfId:
          type: string
          pattern: "^[0-9a-fA-F]{6}$"

    PlmnId:
      type: object
      required: [mcc, mnc]
      properties:
        mcc:
          type: string
          pattern: "^[0-9]{3}$"
        mnc:
          type: string
          pattern: "^[0-9]{2,3}$"

    AssignEbiData:
      type: object
      required: [pduSessionId]
      properties:
        pduSessionId:
          type: integer
          minimum: 1
          maximum: 255

    AssignedEbiData:
      type: object
      properties:
        pduSessionId:
          type: integer
        assignedEbiList:
          type: array
          items:
            type: integer

    UeContextTransferReqData:
      type: object
      required: [reason, accessType]
      properties:
        reason:
          type: string
          enum: [INIT_REG, MOBI_REG, MOBI_REG_UE_VALIDATED]
        accessType:
          type: string
          enum: [3GPP_ACCESS, NON_3GPP_ACCESS]

    UeContextTransferRspData:
      type: object
      properties:
        ueContext:
          $ref: "#/components/schemas/UeContext"

    N2InformationTransferReqData:
      type: object
      properties:
        n2InformationClass:
          type: string
          enum: [SM, RAN, NRPPa, PWS, ATSSS]

    N2InformationTransferRspData:
      type: object
      properties:
        result:
          type: string
          enum: [SUCCESS, FAILURE]

    SubscriptionData:
      type: object
      properties:
        amfStatusUri:
          type: string
          format: uri
        guamiList:
          type: array
          items:
            $ref: "#/components/schemas/Guami"

    ProblemDetails:
      type: object
      properties:
        type:
          type: string
        title:
          type: string
        status:
          type: integer
        detail:
          type: string

  responses:
    NotFound:
      description: Resource not found
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/ProblemDetails"
