# NextGCore EES Edge Enabler Server Service OpenAPI Specification
# G34: OpenAPI specs for remaining SBI services
# Based on 3GPP TS 29.558 v18.6.0

openapi: 3.0.3
info:
  title: EES Edge Enabler Server Service
  version: 1.3.0
  description: EES Edge Enabler Server Service (nees-eediscovery) per 3GPP TS 29.558

servers:
  - url: "{apiRoot}/nees-eediscovery/v1"
    variables:
      apiRoot:
        default: http://localhost:7777

paths:
  /ees-profiles:
    get:
      summary: Discover available EES instances
      operationId: DiscoverEESProfiles
      parameters:
        - name: ue-location
          in: query
          schema:
            type: string
        - name: app-id
          in: query
          schema:
            type: string
        - name: s-nssai
          in: query
          schema:
            type: string
      responses:
        "200":
          description: List of available EES profiles
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/EESProfile"
        "400":
          $ref: "#/components/responses/BadRequest"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/InternalError"

  /ees-profiles/{eesId}:
    get:
      summary: Get specific EES profile
      operationId: GetEESProfile
      parameters:
        - $ref: "#/components/parameters/EesId"
      responses:
        "200":
          description: EES profile retrieved
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EESProfile"
        "404":
          $ref: "#/components/responses/NotFound"

  /subscriptions:
    post:
      summary: Subscribe to EES discovery notifications
      operationId: CreateEESDiscoverySubscription
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/EESDiscoverySubscription"
      responses:
        "201":
          description: Subscription created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EESDiscoverySubscription"
          headers:
            Location:
              description: URI of created subscription
              schema:
                type: string
        "400":
          $ref: "#/components/responses/BadRequest"

  /subscriptions/{subscriptionId}:
    delete:
      summary: Unsubscribe from EES discovery
      operationId: DeleteEESDiscoverySubscription
      parameters:
        - $ref: "#/components/parameters/SubscriptionId"
      responses:
        "204":
          description: Subscription deleted
        "404":
          $ref: "#/components/responses/NotFound"

components:
  parameters:
    EesId:
      name: eesId
      in: path
      required: true
      schema:
        type: string

    SubscriptionId:
      name: subscriptionId
      in: path
      required: true
      schema:
        type: string

  schemas:
    EESProfile:
      type: object
      required:
        - eesId
        - endPoint
      properties:
        eesId:
          type: string
        endPoint:
          type: string
          format: uri
        servingArea:
          type: array
          items:
            type: string
        supportedAppIds:
          type: array
          items:
            type: string
        capabilities:
          type: array
          items:
            type: string

    EESDiscoverySubscription:
      type: object
      required:
        - notificationUri
      properties:
        subscriptionId:
          type: string
        notificationUri:
          type: string
          format: uri
        appId:
          type: string
        ueLocation:
          type: string
        expiryTime:
          type: string
          format: date-time

    ProblemDetails:
      type: object
      properties:
        type:
          type: string
        title:
          type: string
        status:
          type: integer
        detail:
          type: string
        instance:
          type: string

  responses:
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ProblemDetails"

    NotFound:
      description: Not found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ProblemDetails"

    InternalError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ProblemDetails"
