# NextGCore LMF Location Service OpenAPI Specification
# G34: OpenAPI specs for remaining SBI services
# Based on 3GPP TS 29.572 v18.6.0

openapi: 3.0.3
info:
  title: LMF Location Service
  version: 1.3.0
  description: LMF Location Service (nlmf-location) per 3GPP TS 29.572

servers:
  - url: "{apiRoot}/nlmf-loc/v1"
    variables:
      apiRoot:
        default: http://localhost:7777

paths:
  /determine-location:
    post:
      summary: Determine UE location
      operationId: DetermineLocation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LocationRequest"
      responses:
        "200":
          description: Location determined
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LocationInfo"
        "400":
          $ref: "#/components/responses/BadRequest"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/InternalError"

  /provide-location-info:
    post:
      summary: Provide location information
      operationId: ProvideLocationInfo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProvideLocationRequest"
      responses:
        "200":
          description: Location info provided
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LocationInfo"
        "400":
          $ref: "#/components/responses/BadRequest"

  /location-updates/{transactionId}:
    delete:
      summary: Cancel location update
      operationId: CancelLocation
      parameters:
        - $ref: "#/components/parameters/TransactionId"
      responses:
        "204":
          description: Location update cancelled
        "404":
          $ref: "#/components/responses/NotFound"

components:
  parameters:
    TransactionId:
      name: transactionId
      in: path
      required: true
      schema:
        type: string

  schemas:
    LocationRequest:
      type: object
      required:
        - supi
        - lcsServiceType
      properties:
        supi:
          type: string
        lcsServiceType:
          type: string
          enum:
            - EMERGENCY_SERVICES
            - EMERGENCY_ALERT_SERVICES
            - PERSON_TRACKING
            - FLEET_MANAGEMENT
            - ASSET_MANAGEMENT
            - TRAFFIC_CONGESTION_REPORTING
        lcsQos:
          $ref: "#/components/schemas/LocationQos"
        supportedGADShapes:
          type: array
          items:
            type: string

    ProvideLocationRequest:
      type: object
      required:
        - supi
      properties:
        supi:
          type: string
        locationEstimate:
          $ref: "#/components/schemas/GeographicArea"
        accuracyFulfilmentIndicator:
          type: string
          enum:
            - REQUESTED_ACCURACY_FULFILLED
            - REQUESTED_ACCURACY_NOT_FULFILLED

    LocationInfo:
      type: object
      properties:
        locationEstimate:
          $ref: "#/components/schemas/GeographicArea"
        accuracyFulfilmentIndicator:
          type: string
        ageOfLocationEstimate:
          type: integer
        velocityEstimate:
          type: string
        civicAddress:
          type: string

    LocationQos:
      type: object
      properties:
        hAccuracy:
          type: integer
          description: Horizontal accuracy in meters
        vAccuracy:
          type: integer
          description: Vertical accuracy in meters
        responseTime:
          type: string
          enum:
            - LOW_DELAY
            - DELAY_TOLERANT

    GeographicArea:
      type: object
      properties:
        shape:
          type: string
          enum:
            - POINT
            - POINT_UNCERTAINTY_CIRCLE
            - POINT_UNCERTAINTY_ELLIPSE
            - POLYGON
            - POINT_ALTITUDE
            - POINT_ALTITUDE_UNCERTAINTY
            - ELLIPSOID_ARC
        point:
          $ref: "#/components/schemas/GeographicalCoordinates"
        uncertainty:
          type: number
        altitude:
          type: number

    GeographicalCoordinates:
      type: object
      required:
        - lat
        - lon
      properties:
        lat:
          type: number
          minimum: -90
          maximum: 90
        lon:
          type: number
          minimum: -180
          maximum: 180

    ProblemDetails:
      type: object
      properties:
        type:
          type: string
        title:
          type: string
        status:
          type: integer
        detail:
          type: string
        instance:
          type: string

  responses:
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ProblemDetails"

    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ProblemDetails"

    NotFound:
      description: Not found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ProblemDetails"

    InternalError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ProblemDetails"
