# NextGCore NSACF Slice Authentication Service OpenAPI Specification
# G34: OpenAPI specs for remaining SBI services
# Based on 3GPP TS 29.526 v18.6.0

openapi: 3.0.3
info:
  title: NSACF Slice Authentication Service
  version: 1.3.0
  description: NSACF Network Slice Admission Control Service (nnsacf-sliceauth) per 3GPP TS 29.526

servers:
  - url: "{apiRoot}/nnsacf-sliceauth/v1"
    variables:
      apiRoot:
        default: http://localhost:7777

paths:
  /slice-authentications:
    post:
      summary: Request slice authentication
      operationId: SliceAuthentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SliceAuthRequest"
      responses:
        "200":
          description: Slice authentication decision
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SliceAuthResponse"
        "400":
          $ref: "#/components/responses/BadRequest"
        "403":
          $ref: "#/components/responses/Forbidden"
        "500":
          $ref: "#/components/responses/InternalError"

  /slice-authentications/{authId}:
    put:
      summary: Update slice authentication
      operationId: UpdateSliceAuthentication
      parameters:
        - $ref: "#/components/parameters/AuthId"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SliceAuthUpdate"
      responses:
        "200":
          description: Authentication updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SliceAuthResponse"
        "404":
          $ref: "#/components/responses/NotFound"

    delete:
      summary: Revoke slice authentication
      operationId: RevokeSliceAuthentication
      parameters:
        - $ref: "#/components/parameters/AuthId"
      responses:
        "204":
          description: Authentication revoked
        "404":
          $ref: "#/components/responses/NotFound"

components:
  parameters:
    AuthId:
      name: authId
      in: path
      required: true
      schema:
        type: string

  schemas:
    SliceAuthRequest:
      type: object
      required:
        - supi
        - snssai
      properties:
        supi:
          type: string
        snssai:
          $ref: "#/components/schemas/Snssai"
        nfId:
          type: string
        plmnId:
          $ref: "#/components/schemas/PlmnId"

    SliceAuthResponse:
      type: object
      properties:
        authId:
          type: string
        authResult:
          type: string
          enum:
            - AUTHORIZED
            - NOT_AUTHORIZED
        allowedSnssai:
          $ref: "#/components/schemas/Snssai"
        rejectionCause:
          type: string

    SliceAuthUpdate:
      type: object
      properties:
        authStatus:
          type: string
          enum:
            - ACTIVE
            - REVOKED

    Snssai:
      type: object
      required:
        - sst
      properties:
        sst:
          type: integer
          minimum: 0
          maximum: 255
        sd:
          type: string
          pattern: '^[0-9A-F]{6}$'

    PlmnId:
      type: object
      required:
        - mcc
        - mnc
      properties:
        mcc:
          type: string
          pattern: '^[0-9]{3}$'
        mnc:
          type: string
          pattern: '^[0-9]{2,3}$'

    ProblemDetails:
      type: object
      properties:
        type:
          type: string
        title:
          type: string
        status:
          type: integer
        detail:
          type: string
        instance:
          type: string

  responses:
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ProblemDetails"

    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ProblemDetails"

    NotFound:
      description: Not found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ProblemDetails"

    InternalError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ProblemDetails"
