# NextGCore NWDAF Analytics Info Service OpenAPI Specification
# G34: OpenAPI specs for remaining SBI services
# Based on 3GPP TS 29.520 v18.6.0

openapi: 3.0.3
info:
  title: NWDAF Analytics Info Service
  version: 1.3.0
  description: NWDAF Analytics Info Service (nnwdaf-analyticsinfo) per 3GPP TS 29.520

servers:
  - url: "{apiRoot}/nnwdaf-analyticsinfo/v1"
    variables:
      apiRoot:
        default: http://localhost:7777

paths:
  /analytics:
    post:
      summary: Request analytics
      operationId: RequestAnalytics
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AnalyticsRequest"
      responses:
        "200":
          description: Analytics provided
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AnalyticsData"
        "400":
          $ref: "#/components/responses/BadRequest"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/InternalError"

  /analytics-subscriptions:
    post:
      summary: Subscribe to analytics
      operationId: CreateAnalyticsSubscription
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AnalyticsSubscription"
      responses:
        "201":
          description: Analytics subscription created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AnalyticsSubscription"
          headers:
            Location:
              description: URI of created subscription
              schema:
                type: string
        "400":
          $ref: "#/components/responses/BadRequest"
        "500":
          $ref: "#/components/responses/InternalError"

  /analytics-subscriptions/{subscriptionId}:
    delete:
      summary: Unsubscribe from analytics
      operationId: DeleteAnalyticsSubscription
      parameters:
        - $ref: "#/components/parameters/SubscriptionId"
      responses:
        "204":
          description: Subscription deleted
        "404":
          $ref: "#/components/responses/NotFound"

components:
  parameters:
    SubscriptionId:
      name: subscriptionId
      in: path
      required: true
      schema:
        type: string

  schemas:
    AnalyticsRequest:
      type: object
      properties:
        analyticsId:
          type: string
          enum:
            - LOAD_LEVEL_INFORMATION
            - NETWORK_PERFORMANCE
            - NF_LOAD
            - SERVICE_EXPERIENCE
            - UE_MOBILITY
            - UE_COMMUNICATION
        targetOfAnalyticsIds:
          type: array
          items:
            type: string
        timeRange:
          $ref: "#/components/schemas/TimeWindow"

    AnalyticsData:
      type: object
      properties:
        analyticsId:
          type: string
        sliceLoadLevelInfo:
          type: object
        networkPerfInfo:
          type: object
        nfLoadLevelInfo:
          type: object
        serviceExperience:
          type: object

    AnalyticsSubscription:
      type: object
      required:
        - analyticsIds
        - notificationUri
      properties:
        subscriptionId:
          type: string
        analyticsIds:
          type: array
          items:
            type: string
        notificationUri:
          type: string
          format: uri
        targetOfAnalyticsIds:
          type: array
          items:
            type: string

    TimeWindow:
      type: object
      properties:
        startTime:
          type: string
          format: date-time
        stopTime:
          type: string
          format: date-time

    ProblemDetails:
      type: object
      properties:
        type:
          type: string
        title:
          type: string
        status:
          type: integer
        detail:
          type: string
        instance:
          type: string

  responses:
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ProblemDetails"

    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ProblemDetails"

    NotFound:
      description: Not found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ProblemDetails"

    InternalError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ProblemDetails"
