# NextGCore PIN Personal IoT Network Event Exposure Service OpenAPI Specification
# G34: OpenAPI specs for remaining SBI services
# Based on 3GPP TS 29.549 v18.6.0

openapi: 3.0.3
info:
  title: PIN Event Exposure Service
  version: 1.3.0
  description: PIN Personal IoT Network Event Exposure Service (npin-eventexposure) per 3GPP TS 29.549

servers:
  - url: "{apiRoot}/npin-ee/v1"
    variables:
      apiRoot:
        default: http://localhost:7777

paths:
  /subscriptions:
    post:
      summary: Subscribe to PIN events
      operationId: CreatePINSubscription
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PINEventSubscription"
      responses:
        "201":
          description: Subscription created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PINEventSubscription"
          headers:
            Location:
              description: URI of created subscription
              schema:
                type: string
        "400":
          $ref: "#/components/responses/BadRequest"
        "500":
          $ref: "#/components/responses/InternalError"

  /subscriptions/{subscriptionId}:
    get:
      summary: Get PIN event subscription
      operationId: GetPINSubscription
      parameters:
        - $ref: "#/components/parameters/SubscriptionId"
      responses:
        "200":
          description: Subscription retrieved
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PINEventSubscription"
        "404":
          $ref: "#/components/responses/NotFound"

    put:
      summary: Update PIN event subscription
      operationId: UpdatePINSubscription
      parameters:
        - $ref: "#/components/parameters/SubscriptionId"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PINEventSubscription"
      responses:
        "200":
          description: Subscription updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PINEventSubscription"
        "404":
          $ref: "#/components/responses/NotFound"

    delete:
      summary: Unsubscribe from PIN events
      operationId: DeletePINSubscription
      parameters:
        - $ref: "#/components/parameters/SubscriptionId"
      responses:
        "204":
          description: Subscription deleted
        "404":
          $ref: "#/components/responses/NotFound"

  /pin-elements:
    get:
      summary: Get PIN element information
      operationId: GetPINElements
      parameters:
        - name: pin-element-id
          in: query
          schema:
            type: string
        - name: dddTrafficDescriptor
          in: query
          schema:
            type: string
      responses:
        "200":
          description: PIN element list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/PINElementInfo"
        "400":
          $ref: "#/components/responses/BadRequest"

components:
  parameters:
    SubscriptionId:
      name: subscriptionId
      in: path
      required: true
      schema:
        type: string

  schemas:
    PINEventSubscription:
      type: object
      required:
        - eventType
        - notificationUri
      properties:
        subscriptionId:
          type: string
        eventType:
          type: string
          enum:
            - PIN_ELEMENT_REGISTRATION
            - PIN_ELEMENT_DEREGISTRATION
            - PIN_TOPOLOGY_CHANGE
            - DDD_TRAFFIC_DESCRIPTOR_UPDATE
        notificationUri:
          type: string
          format: uri
        pinElementId:
          type: string
        expiryTime:
          type: string
          format: date-time

    PINElementInfo:
      type: object
      properties:
        pinElementId:
          type: string
        dddTrafficDescriptor:
          type: string
        pinElementType:
          type: string
          enum:
            - PKMF
            - DDNMF
            - PVSF
        registrationStatus:
          type: string
          enum:
            - REGISTERED
            - DEREGISTERED
        servingPlmnId:
          $ref: "#/components/schemas/PlmnId"

    PlmnId:
      type: object
      required:
        - mcc
        - mnc
      properties:
        mcc:
          type: string
          pattern: '^[0-9]{3}$'
        mnc:
          type: string
          pattern: '^[0-9]{2,3}$'

    ProblemDetails:
      type: object
      properties:
        type:
          type: string
        title:
          type: string
        status:
          type: integer
        detail:
          type: string
        instance:
          type: string

  responses:
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ProblemDetails"

    NotFound:
      description: Not found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ProblemDetails"

    InternalError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ProblemDetails"
