# NextGCore SMF PDU Session Service OpenAPI Specification
# Based on 3GPP TS 29.502 v18.6.0

openapi: 3.0.3
info:
  title: SMF PDU Session Service
  version: 1.3.0
  description: SMF PDU Session Service (nsmf-pdusession) per 3GPP TS 29.502

servers:
  - url: "{apiRoot}/nsmf-pdusession/v1"
    variables:
      apiRoot:
        default: http://localhost:7777

paths:
  /sm-contexts:
    post:
      summary: Create SM context
      operationId: PostSmContexts
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SmContextCreateData"
      responses:
        "201":
          description: SM context created
          headers:
            Location:
              schema:
                type: string
                format: uri
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SmContextCreatedData"
        "400":
          $ref: "#/components/responses/BadRequest"

  /sm-contexts/{smContextRef}/modify:
    post:
      summary: Modify SM context
      operationId: UpdateSmContext
      parameters:
        - $ref: "#/components/parameters/SmContextRef"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SmContextUpdateData"
      responses:
        "200":
          description: SM context updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SmContextUpdatedData"

  /sm-contexts/{smContextRef}/release:
    post:
      summary: Release SM context
      operationId: ReleaseSmContext
      parameters:
        - $ref: "#/components/parameters/SmContextRef"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SmContextReleaseData"
      responses:
        "204":
          description: SM context released

  /pdu-sessions:
    post:
      summary: Create PDU session (N16)
      operationId: PostPduSessions
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PduSessionCreateData"
      responses:
        "201":
          description: PDU session created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PduSessionCreatedData"

components:
  parameters:
    SmContextRef:
      name: smContextRef
      in: path
      required: true
      schema:
        type: string

  schemas:
    SmContextCreateData:
      type: object
      required:
        - supi
        - pduSessionId
        - dnn
        - sNssai
        - servingNfId
        - anType
      properties:
        supi:
          type: string
        pei:
          type: string
        pduSessionId:
          type: integer
          minimum: 1
          maximum: 255
        dnn:
          type: string
        sNssai:
          $ref: "#/components/schemas/Snssai"
        servingNfId:
          type: string
          format: uuid
        anType:
          type: string
          enum: [3GPP_ACCESS, NON_3GPP_ACCESS]
        requestType:
          type: string
          enum: [INITIAL_REQUEST, EXISTING_PDU_SESSION, MODIFICATION_REQUEST]

    SmContextCreatedData:
      type: object
      properties:
        hSmfUri:
          type: string
          format: uri
        pduSessionId:
          type: integer
        sNssai:
          $ref: "#/components/schemas/Snssai"
        upCnxState:
          type: string
          enum: [ACTIVATING, ACTIVATED, DEACTIVATED, SUSPENDED]
        allocatedEbiList:
          type: array
          items:
            type: integer

    SmContextUpdateData:
      type: object
      properties:
        pei:
          type: string
        upCnxState:
          type: string
          enum: [ACTIVATING, ACTIVATED, DEACTIVATED, SUSPENDED]
        anType:
          type: string
          enum: [3GPP_ACCESS, NON_3GPP_ACCESS]
        ratType:
          type: string
          enum: [NR, EUTRA, WLAN, VIRTUAL]
        n2SmInfo:
          type: string
          format: binary
        n2SmInfoType:
          type: string
          enum:
            - PDU_RES_SETUP_RSP
            - PDU_RES_REL_RSP
            - PDU_RES_MOD_RSP
            - PATH_SWITCH_REQ
            - HANDOVER_REQUIRED
            - HANDOVER_REQ_ACK

    SmContextUpdatedData:
      type: object
      properties:
        upCnxState:
          type: string
          enum: [ACTIVATING, ACTIVATED, DEACTIVATED, SUSPENDED]
        n2SmInfo:
          type: string
          format: binary
        n2SmInfoType:
          type: string

    SmContextReleaseData:
      type: object
      properties:
        cause:
          type: string
          enum:
            - REL_DUE_TO_HO
            - REL_DUE_TO_UP_SEC
            - REL_DUE_TO_NGRAN_REASON
            - REL_DUE_TO_5GC_DECISION
            - REL_DUE_TO_SLICE_NOT_AVAILABLE
            - REL_DUE_TO_DUPLICATE_SESSION_ID
        ngApCause:
          type: object
          properties:
            group:
              type: integer
            value:
              type: integer

    PduSessionCreateData:
      type: object
      required: [pduSessionId, dnn, sNssai]
      properties:
        pduSessionId:
          type: integer
        dnn:
          type: string
        sNssai:
          $ref: "#/components/schemas/Snssai"
        pduSessionType:
          type: string
          enum: [IPV4, IPV6, IPV4V6, UNSTRUCTURED, ETHERNET]

    PduSessionCreatedData:
      type: object
      properties:
        pduSessionType:
          type: string
        sscMode:
          type: string
          enum: ["1", "2", "3"]
        sessionAmbr:
          $ref: "#/components/schemas/Ambr"

    Snssai:
      type: object
      required: [sst]
      properties:
        sst:
          type: integer
          minimum: 0
          maximum: 255
        sd:
          type: string
          pattern: "^[0-9a-fA-F]{6}$"

    Ambr:
      type: object
      properties:
        uplink:
          type: string
        downlink:
          type: string

    ProblemDetails:
      type: object
      properties:
        type:
          type: string
        title:
          type: string
        status:
          type: integer
        detail:
          type: string

  responses:
    BadRequest:
      description: Bad request
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/ProblemDetails"
