# NextGCore UDM Subscriber Data Management Service OpenAPI Specification
# Based on 3GPP TS 29.503 v18.6.0

openapi: 3.0.3
info:
  title: UDM Subscriber Data Management Service
  version: 1.3.0
  description: UDM SDM Service (nudm-sdm) per 3GPP TS 29.503

servers:
  - url: "{apiRoot}/nudm-sdm/v2"
    variables:
      apiRoot:
        default: http://localhost:7777

paths:
  /{supi}:
    get:
      summary: Get subscriber data
      operationId: GetSupiInfo
      parameters:
        - $ref: "#/components/parameters/Supi"
      responses:
        "200":
          description: Subscriber data retrieved
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SubscriptionDataSets"

  /{supi}/nssai:
    get:
      summary: Get subscribed S-NSSAI
      operationId: GetNssai
      parameters:
        - $ref: "#/components/parameters/Supi"
        - name: plmn-id
          in: query
          schema:
            $ref: "#/components/schemas/PlmnId"
      responses:
        "200":
          description: NSSAI data
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Nssai"

  /{supi}/am-data:
    get:
      summary: Get access and mobility subscription data
      operationId: GetAmData
      parameters:
        - $ref: "#/components/parameters/Supi"
        - name: plmn-id
          in: query
          schema:
            $ref: "#/components/schemas/PlmnId"
      responses:
        "200":
          description: AM subscription data
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AccessAndMobilitySubscriptionData"

  /{supi}/sm-data:
    get:
      summary: Get session management subscription data
      operationId: GetSmData
      parameters:
        - $ref: "#/components/parameters/Supi"
        - name: dnn
          in: query
          schema:
            type: string
        - name: single-nssai
          in: query
          schema:
            $ref: "#/components/schemas/Snssai"
      responses:
        "200":
          description: SM subscription data
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/SessionManagementSubscriptionData"

  /{supi}/sdm-subscriptions:
    post:
      summary: Subscribe to data change notifications
      operationId: Subscribe
      parameters:
        - $ref: "#/components/parameters/Supi"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SdmSubscription"
      responses:
        "201":
          description: Subscription created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SdmSubscription"

components:
  parameters:
    Supi:
      name: supi
      in: path
      required: true
      schema:
        type: string
        pattern: "^(imsi-[0-9]{5,15}|nai-.+)$"

  schemas:
    SubscriptionDataSets:
      type: object
      properties:
        amData:
          $ref: "#/components/schemas/AccessAndMobilitySubscriptionData"
        smfSelData:
          $ref: "#/components/schemas/SmfSelectionSubscriptionData"

    AccessAndMobilitySubscriptionData:
      type: object
      properties:
        supportedFeatures:
          type: string
        gpsis:
          type: array
          items:
            type: string
        subscribedUeAmbr:
          $ref: "#/components/schemas/Ambr"
        nssai:
          $ref: "#/components/schemas/Nssai"
        ratRestrictions:
          type: array
          items:
            type: string
            enum: [NR, EUTRA, WLAN, VIRTUAL]

    SessionManagementSubscriptionData:
      type: object
      properties:
        singleNssai:
          $ref: "#/components/schemas/Snssai"
        dnnConfigurations:
          type: object
          additionalProperties:
            $ref: "#/components/schemas/DnnConfiguration"

    DnnConfiguration:
      type: object
      properties:
        pduSessionTypes:
          type: object
          properties:
            defaultSessionType:
              type: string
              enum: [IPV4, IPV6, IPV4V6, UNSTRUCTURED, ETHERNET]
            allowedSessionTypes:
              type: array
              items:
                type: string
        sscModes:
          type: object
          properties:
            defaultSscMode:
              type: string
              enum: ["1", "2", "3"]
            allowedSscModes:
              type: array
              items:
                type: string
        sessionAmbr:
          $ref: "#/components/schemas/Ambr"
        fiveGQosProfile:
          $ref: "#/components/schemas/FiveGQosProfile"

    FiveGQosProfile:
      type: object
      properties:
        fiveQi:
          type: integer
          minimum: 0
          maximum: 255
        priorityLevel:
          type: integer

    SmfSelectionSubscriptionData:
      type: object
      properties:
        subscribedSnssaiInfos:
          type: object
          additionalProperties:
            $ref: "#/components/schemas/SnssaiInfo"

    SnssaiInfo:
      type: object
      properties:
        dnnInfos:
          type: array
          items:
            type: object
            properties:
              dnn:
                type: string

    Nssai:
      type: object
      properties:
        defaultSingleNssais:
          type: array
          items:
            $ref: "#/components/schemas/Snssai"
        singleNssais:
          type: array
          items:
            $ref: "#/components/schemas/Snssai"

    PlmnId:
      type: object
      required: [mcc, mnc]
      properties:
        mcc:
          type: string
          pattern: "^[0-9]{3}$"
        mnc:
          type: string
          pattern: "^[0-9]{2,3}$"

    Snssai:
      type: object
      required: [sst]
      properties:
        sst:
          type: integer
          minimum: 0
          maximum: 255
        sd:
          type: string
          pattern: "^[0-9a-fA-F]{6}$"

    Ambr:
      type: object
      properties:
        uplink:
          type: string
        downlink:
          type: string

    SdmSubscription:
      type: object
      required: [nfInstanceId, callbackReference, monitoredResourceUris]
      properties:
        nfInstanceId:
          type: string
          format: uuid
        callbackReference:
          type: string
          format: uri
        monitoredResourceUris:
          type: array
          items:
            type: string
            format: uri
        expires:
          type: string
          format: date-time
