[package]
name = "nextgcore-hssd"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "NextGCore HSS (Home Subscriber Server)"

[[bin]]
name = "nextgcore-hssd"
path = "src/main.rs"

[dependencies]
nextgcore-core = { workspace = true }
nextgcore-crypt = { workspace = true }
nextgcore-diameter = { workspace = true }
nextgcore-dbi = { workspace = true }
nextgcore-app = { workspace = true }
nextgcore-metrics = { workspace = true }
bytes.workspace = true
log.workspace = true
rand = { workspace = true }
env_logger.workspace = true
tokio.workspace = true
anyhow.workspace = true
clap = { workspace = true, features = ["derive"] }
ctrlc.workspace = true

[dev-dependencies]
proptest.workspace = true

[lints]
workspace = true
