{{- if .Values.nrf.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-nrf
  labels:
    app.kubernetes.io/name: nrf
    app.kubernetes.io/instance: {{ .Release.Name }}-nrf
    app.kubernetes.io/component: control-plane
    {{- include "nextgcore.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.nrf.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: nrf
      app.kubernetes.io/instance: {{ .Release.Name }}-nrf
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nrf
        app.kubernetes.io/instance: {{ .Release.Name }}-nrf
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      {{- if .Values.mongodb.enabled }}
      initContainers:
        {{- include "nextgcore.waitForMongo" . | nindent 8 }}
      {{- end }}
      containers:
        - name: nrf
          image: {{ include "nextgcore.image" (dict "global" .Values.global "nf" .Values.nrf) }}
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          args: ["-c", "/etc/nextgcore/nrf.yaml"]
          ports:
            - name: sbi
              containerPort: {{ .Values.nrf.service.port }}
              protocol: TCP
            {{- if .Values.nrf.metrics.enabled }}
            - name: metrics
              containerPort: {{ .Values.nrf.metrics.port }}
              protocol: TCP
            {{- end }}
          {{- include "nextgcore.sbiProbes" . | nindent 10 }}
          volumeMounts:
            {{- include "nextgcore.configMounts" (dict "nf" "nrf" "rewritten" false) | nindent 12 }}
          env:
            - name: RUST_LOG
              value: {{ .Values.global.logLevel }}
      volumes:
        {{- include "nextgcore.configVolumes" . | nindent 8 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nrf
  labels:
    app.kubernetes.io/name: nrf
    {{- include "nextgcore.labels" . | nindent 4 }}
spec:
  type: {{ .Values.nrf.service.type }}
  ports:
    - port: {{ .Values.nrf.service.port }}
      targetPort: sbi
      protocol: TCP
      name: sbi
    {{- if .Values.nrf.metrics.enabled }}
    - port: {{ .Values.nrf.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    app.kubernetes.io/name: nrf
    app.kubernetes.io/instance: {{ .Release.Name }}-nrf
{{- end }}
