# LMF (Location Management Function) Configuration
logger:
  level: info

lmf:
  sbi:
    server:
      - address: 0.0.0.0
        advertise: 172.23.0.32
        port: 7777
  nrf:
    uri: http://172.23.0.10:7777
